matrix:
  include:
    - language: android
      dist: trusty
      android:
        components:
          - build-tools-26.0.2
          - android-26
          - extra
    - language: java
      jdk:
        - openjdk11
before_install:
  - wget http://services.gradle.org/distributions/gradle-5.6.2-bin.zip
  - unzip -qq gradle-5.6.2-bin.zip
  - export GRADLE_HOME=$PWD/gradle-5.6.2
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v
script:
  - mvn clean install
  - cd itf-chartizate-android
  - gradle clean build

