language: java
jdk:
  - openjdk11
script:
  - sudo add-apt-repository ppa:cwchien/gradle
  - sudo apt-get update
  - sudo apt upgrade gradle
  - mvn clean install
  - cd itf-chartizate-android
  - gradle clean build

