matrix:
  include:
    - language: android
      dist: trusty
      android:
        components:
          - build-tools-29.0.0
          - android-29
          - extra
      before_install:
        - wget http://services.gradle.org/distributions/gradle-5.6.2-bin.zip
        - unzip -qq gradle-5.6.2-bin.zip
        - export GRADLE_HOME=$PWD/gradle-5.6.2
        - export PATH=$GRADLE_HOME/bin:$PATH
        - gradle -v
        - brew tap caskroom/versions
        - brew cask info java11
        - brew cask info java
        - brew cask install java11
        - brew cask install java
      script:
        - mvn clean install -DskipTests
        - cd itf-chartizate-android
        - touch local.properties
        - gradle clean build
    - language: java
      jdk:
        - openjdk11
      script:
        - mvn clean install



